### ISSUE TITLE
tests failed

### ISSUE THREAD

**Issue by anhanijr** [cyverseuk/polymarker#1]
Hi

I've just installed Polymarker, and tests failed...

[tests_fail.log](https://github.com/cyverseuk/polymarker/files/1435002/tests_fail.log)

**Comment by aliceminotto** [comment]
Hi

Did you installed polymarker directly? The CyVerse app is now on hold waiting for the new stable release. If you have problem with an installation on your laptop/HPC system I'd suggest you to open an issue here: https://github.com/TGAC/bioruby-polyploid-tools and Ricardo may be able to help you find the right version to install.

**Comment by anhanijr** [comment]
Hi Alice,
Thanks for such fast response!
Yes i believe, using " sudo gem install..." inside downloaded folder.
Originaly i posted to  bio-polyploid-tools, but thought here would be better directed to polymarker...

Best wishes,

Antonio

**Comment by aliceminotto** [comment]
this issue needs to be solved in TGAC/bioruby-polyploid-tools#10
will close here as it's not an issue with the docker image.
